# Generated by Django 2.2.7 on 2019-11-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=125)),
                ('nb_stars', models.IntegerField()),
                ('time', models.TimeField()),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Level')),
            ],
        ),
    ]
