# Generated by Django 2.2.7 on 2019-12-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.World'),
            preserve_default=False,
        ),
    ]
